from numpy import random
import pandas as pd

def generateDB():

    # Reading symbols from the csv generated by fractal distribution
    df = pd.read_csv('symbols.csv')
    symbols = df.to_numpy()
    symbols = symbols.flatten()
    symbolslen = len(symbols)

    transactiontype = ['cash', 'cheque', 'money order', 'online payment', 'margin', 'credit']
    totaltypes = len(transactiontype) - 1
    # Defining Column names and total rows
    columns = ["stocksymbol", "time", "quantity", "price", "transaction"]
    tot_rows = 40000000
    data = []

    # Variables to keep track of rows generated and current prices of stocks
    i = 0
    price = {}

    while(i <= tot_rows) :
        j = i%symbolslen # moding to adjust ranges

        new_price = price[symbols[j]]+1 if symbols[j] in price else random.randint(50, 501, 1)[0] # randomly generating if the symbol has no previous price val

        if new_price > 500 : # reset price if not in range
            new_price = 50

        price[symbols[j]] = new_price

        quantity = random.randint(100, 10001, 1)[0]
        type = transactiontype[random.randint(0, totaltypes, 1)[0]]
        id = 's'+str(symbols[j])
        data.append([id, i+1, quantity, new_price, type]) # setting newly generated row data
        i+=1
    
    df = pd.DataFrame(data)
    df.to_csv('data.csv', index=False, header=columns) # aving data in csv
        
generateDB()